### ISSUE TITLE
Will the linker support Microsoft pe objects in the future?

### ISSUE THREAD

**Issue by icyfox168168** [lasarus/C-Compiler#4]
Will the linker support Microsoft pe objects in the future?

**Comment by lasarus** [comment]
Maybe. The object/executable implementation is meant to be flexible, but I won't promise anything.

**Comment by icyfox168168** [comment]
In the previous version, the parameter compilation is normal

There is an error in the current version

bddisasm

-c -fabi=ms -fdebug-stack-size=20480     -fcmodel=large
nd_strcat_s

Internal compiler error on line 273 file src/linker/coff.c of compiler source: "Not implemented"

**Comment by icyfox168168** [comment]
nd_strcat_s  in bddisasmTest.c
gcc bddisasmTest.c crt.o bddisasm.o bdformat.o bdhelpers.o bdshemu.o -o bddisasm_o_Test.exe

**Comment by icyfox168168** [comment]
In file included from src/linker/elf.c:3:
src/linker/elf.c: In function 'object_from_elf':
src/common.h:10:35: warning: format '%lu' expects argument of type 'long unsigned int', but argument 4 has type 'uint64_t' {aka 'long long unsigned int'} [-Wformat=]
   10 | #define ICE(STR, ...) do { printf("\nInternal compiler error on line %d file %s of compiler source: \"" STR "\"\n", __LINE__, __FILE__, ##__VA_ARGS__); exit(1); } while(0)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/common.h:10:35: note: in definition of macro 'ICE'
   10 | #define ICE(STR, ...) do { printf("\nInternal compiler error on line %d file %s of compiler source: \"" STR "\"\n", __LINE__, __FILE__, ##__VA_ARGS__); exit(1); } while(0)
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/linker/elf.c:288:23: note: format string is defined here
  288 |     ICE("Relocation %lu not implemented.", r_info & 0xffff);
      |                     ~~^
      |                       |
      |                       long unsigned int
      |                     %llu

**Comment by lasarus** [comment]
> Internal compiler error on line 273 file src/linker/coff.c of compiler source: "Not implemented"

This should now be fixed.

**Comment by icyfox168168** [comment]
ok

**Comment by lasarus** [comment]
I have only added COFF support for the assembler. The linker is still not able to produce PE executables. It will take some time until the linker is functional.
