### ISSUE TITLE
Readme - mention linker

### ISSUE THREAD

**Issue by andrewchambers** [lasarus/C-Compiler#6]
The readme says it does not include a linker, but it seems to include one.

**Comment by lasarus** [comment]
That is elaborated upon a bit further down in the readme.

> Without any `-S` or `-c` flag, the compiler will try to link the input into an executable elf file.
> The linker is still under development, and will most likely not work for any non-trivial program.

The linker doesn't support very much. Mainly it lacks GOT and PLT support, and thus cannot link against any standard library I know of. I have also lost a bit of interest in further developing it.
